name: Build & Deploy via Infra Repo

on:
  push:
    branches: [ dev ]

permissions:
  contents: write
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout app code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        env:
          IMAGE: ghcr.io/ntgclaritypk/ntg-tickets:${{ github.sha }}
        run: |
          docker build -t $IMAGE .
          docker push $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Clone infra repo
        run: |
          git clone https://$GITHUB_ACTOR:${{ secrets.PERSONAL_TOKEN }}@github.com/syedehsanuddin/infra-repo.git infra
          cd infra
          echo "Infra repo cloned successfully."

      - name: Update deployment image in infra repo
        run: |
          cd infra/apps/ntg-tickets
          sed -i "s|image: .*|image: $IMAGE|" deployment.yaml
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add deployment.yaml
          git commit -m "Update ntg-tickets image to $IMAGE" || echo "No changes to commit"
          git push origin main
